version: "3"
virtualmachines:
- name: metrics-demo
  image: ubuntu:22.04
  shell: /bin/bash
  environment:
    ELASTIC_DATASET: metrics-demo
    DEMO_MODE: firehose
    USE_LOCAL_ELASTIC: "true"
  memory: 4096
  cpus: 2
  allow_external_ingress:
  - http
  - https
  - high-ports
