apiVersion: v1
kind: Secret
metadata:
  name: elastic-otlp-secret
  namespace: elastic-metrics-demo
type: Opaque
stringData:
  # These will be replaced by deploy.sh script
  ELASTIC_OTLP_ENDPOINT: ""
  ELASTIC_API_KEY: ""
  ELASTIC_DATASET: "metrics-demo"
